# Generated by Django 5.2.6 on 2025-09-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetail',
            name='assigned_to',
        ),
    ]
